### ISSUE TITLE
Help reading your code

### ISSUE THREAD

**Issue by lhk** [regnets/Pewduino#1]
I'm trying to create a project similar to yours and have strange problems with IRLib.
Apparently you have had issues with that library, too and managed to solve them: http://forum.arduino.cc/index.php?topic=290311.15

I read up on your code and have the following question:

You have defined constants for marks and spaces compatible to Lightstrike. With these definitions you use sendGeneric and decodeGeneric. But you pass different configurations to the sender and the receiver. On the sending side you use LIGHT_STRIKE_MARK_ONE and on the receiving side just 0.
How does that work, why is it necessary ?

I looked at your IRLib-light and it seems like sendGeneric and decodeGeneric are (almost) identical to the original versions.

I have described my problem in the forum post in more detail and would be very grateful if you could share some experiences.

**Comment by regnets** [comment]
You are absolutely right. 

I got the same issue as you at my first attempts. The solution is described in the comment above decodeGeneric in the original IRLib from cyborg5:

> Again we use a generic routine because most protocols have the same basic structure. However we  need to indicate whether or not the protocol varies the length of the mark or the space to indicate a "0" or "1".
> If "Mark_One" is zero. We assume that the length of the space varies. If "Mark_One" is not zero then
> we assume that the length of Mark varies and the value passed as "Space_Zero" is ignored.
> When using variable length Mark, assumes Head_Space==Space_One. If it doesn't, you need a  specialized decoder.

If you don't pass 0 as MARK_ONE for the decodeGeneric method you will get a "head space error" i think and this will eventuate into a 0 for the result.

I also talked about this with cyborg5 but i can't remember on which plattform (couldn't find it in the arduino forum).

I think his response were that most ir protocols are working that way, but he would like to fix this in the future.

**Comment by lhk** [comment]
Thanks for the quick response. I contacted cyborg5, too. The mark_one zero parameter was not my only problem. I passed the wrong rawcount, too. 
I counted head mark and space = two samples . Mark and space for each bit = 2_numBits samples. And one space at the end. 
That makes 2_numBits +3.
In fact there are 2*numBits +4 raw samples. 

I checked against your code again. You transmit 32 bits of data with a rawcount of 66? 
Strange. I tested with lots of different numBits, from 1 to 10. Anything different from the formula above fails.

**Comment by regnets** [comment]
I thought it should be 66 Samples... 

  Sample 1 Undefined Space (wating for input)
  Sample 2 HEADER_MARK_ONE 
  Sample 3 HEADER_MARK_ZERO
  Sample 4-65 <bits (32*2)>
  Sample 66 Undefined Space.

However i could be wrong, for me this is working perfectly.

**Comment by lhk** [comment]
Well since it is working you must be right. There's no arguing with facts.
But the math doesn't add up. 65-3=62, 62/2=31 
Your signal should only have space for 31 bits of data.

Maybe the last bit has no space, and the waiting for data is no sample ? Then you would have two more samples = 1 bit more for data.

However. With your help, my transmission works now. I passed 0 to the decoder, used the correct number of samples and it works.
Thank you very much.
